name = "manatee-slash"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-03-08"

[build]
command = "yarn install && yarn build"
[build.upload]
format = "service-worker"
